import type { PlanDelivery } from "./plan-publications";
import type { ChirpState } from "./chirp-voices";
import type { Lesson, Course } from "./content";
import type { LessonPreparation } from "./lesson-preparation";
import type { WeeklyRefresh, WeeklyRefreshState } from "./weekly-refresh";
import type { WeeklyBatch, WeeklyChoice } from "./weekly-selection";
export type Progress = { lesson_key: string; position: number; section: number; completed: number; revision: number; observed_at: number };
export type Note = { id: string; lesson_key: string; kind: string; text: string; created_at: number };
export type LearningEvent = { id: string; kind: string; payload: { key: string; supplementId?: string; title?: string; sourceUrl?: string; provider?: string; method?: string; completed?: boolean; answer?: number; correct?: boolean; explanation?: string }; created_at: number };
export type LibraryItem = { refresh_of?: string | null; refresh_hash?: string | null; id: string; kind: "source" | "topic"; title: string; url: string | null; detail: string; status: string; created_at: number };
export type SourceMaterial = { finalUrl: string; title: string; publisher: string; published: string | null; retrievedAt: number; contentType: string; hash: string; bytes: number; truncated: boolean; preview: string };
export type SourceCapture = { id: string; library_item_id: string; requested_url: string; status: "retrieving" | "retrieved" | "unavailable"; result: SourceMaterial | null; error: string | null; created_at: number; finished_at: number | null };
export type ResearchCandidate = { url: string; reason: string; itemId: string; captureId: string };
export type ResearchSearch = { candidates: ResearchCandidate[]; gap: string; consultedUrls: string[]; model: string; searchedAt: number; providerRequest: string | null; providerResponse: string; cost: number; costBasis: string };
export type TopicResearch = { id: string; topic_id: string; title: string; detail: string; search: ResearchSearch | null; error: string | null; created_at: number };
export type CoursePreference = { id: string; active: boolean };
export type AnswerSourceCopy = SourceMaterial & { snapshotId: string; sourceId: string; contextBytes: number; partialContext: boolean };
export type LessonAnswer = { text: string; sourceIds: string[]; needsResearch: boolean; evidence?: { sourceId: string; quote: string }[]; sourceCopies?: AnswerSourceCopy[]; cost: number; costBasis: string; providerRequest: string | null; providerResponse: string; model: string; answeredAt: number };
export type QuestionResearch = { question_id: string; lesson_key: string; question: string; topic_id: string; research_id: string; answer_id: string; sourceCaptureIds: string[] | null; created_at: number };
export type Question = { id: string; lesson_key: string; question: string; sourceCaptureIds: string[]; answer: LessonAnswer | null; created_at: number };
export type CostReview = { id: string; spending_id: string; revision: number; decision: "confirmed" | "keep_reserved"; amount: number | null; evidence: string; created_at: number };
export type NarrationReplacement = { id: string; root_id: string; operation_id: string; parent_id: string; review_id: string; lesson_key: string; part: number; attempt: number; max_cost: number; created_at: number };
export type SpendingRecord = { id: string; month: string; kind: string; status: string; reserved: number; charged: number | null; basis: string; provider_request: string | null; created_at: number; effective: number; fingerprint: string; reviewId: string | null; reviewCurrent: boolean; needsReview: boolean };
export type GenerationState = { job_id: string; token: string; expires_at: number } | null;
export type VoicePurpose = "question" | "reflection" | "challenge";
export type VoiceResult = { text: string; cost: number; costBasis: string; providerRequest: string | null; model: string; transcribedAt: number };
export type VoiceDraft = { id: string; lesson_key: string; purpose: VoicePurpose; duration_ms: number; result: VoiceResult | null; created_at: number };
export type LessonReviewReceipt = {
  method: "build-editorial" | "automated";
  checkedAt: number;
  contentHash: string;
  summary: string;
  preparationId?: string;
  sourceChecks: { id: string; url: string; inspected: string; materialHash: string; snapshotId: string }[];
};
export type LessonRelease = { lesson_key: string; previousKey: string | null; summary: string; createdAt: number; review: LessonReviewReceipt | null };
export type AppState = { planDeliveries?: PlanDelivery[]; chirp: ChirpState; weeklyRefresh: { history: WeeklyRefresh[]; current: WeeklyRefreshState | null }; weekly: { batches: WeeklyBatch[]; choices: WeeklyChoice[] };  questionResearch: QuestionResearch[]; narrationReplacements: NarrationReplacement[]; costReviews: CostReview[]; lessonPreparations: LessonPreparation[]; preparationAllowance: { retained: number; limit: number; thisMonth: number; monthlyLimit: number }; storage: { limit: number; committed: number }; asOf: number; courses: Course[]; coursePreferences: CoursePreference[]; events: LearningEvent[]; libraryItems: LibraryItem[]; sourceCaptures: SourceCapture[]; topicResearch: TopicResearch[]; researchAllowance: { retained: number; limit: number; thisMonth: number; monthlyLimit: number }; sourceAllowance: { retained: number; limit: number; thisMonth: number; monthlyLimit: number }; lessons: Lesson[]; archivedLessons: Lesson[]; releases: LessonRelease[]; progress: Progress[]; notes: Note[]; questions: Question[]; voiceDrafts: VoiceDraft[]; spending: SpendingRecord[]; generation: GenerationState; media: { lesson_key: string; duration: number | null }[]; activity: { minute: number; seconds: number }[]; budget: { limit: number; committed: number; month: string; paused: boolean }; aiConfigured: boolean };
