import type { Source } from "./content";

const inspected = "2026-09-15";
const source = (id: string, title: string, publisher: string, url: string, supports: string): Source => ({ id, title, publisher, url, supports, published: null, inspected });
export const foundationSources = {
  client: source("mdn-client-server", "Client-server overview", "MDN", "https://developer.mozilla.org/en-US/docs/Learn_web_development/Extensions/Server-side/First_steps/Client-Server_overview", "HTTP requests and responses connect the browser, server processing, and stored data."),
  http: source("mdn-http", "Overview of HTTP", "MDN", "https://developer.mozilla.org/en-US/docs/Web/HTTP/Guides/Overview", "HTTP is stateless; cookies can support sessions across requests."),
  retry: source("mdn-idempotent", "Idempotent", "MDN", "https://developer.mozilla.org/en-US/docs/Glossary/Idempotent", "Idempotency concerns the intended server effect of repeated requests, not identical responses."),
  context: source("github-context", "Prompt engineering for GitHub Copilot Chat", "GitHub", "https://docs.github.com/en/enterprise-cloud%40latest/copilot/concepts/prompting/prompt-engineering", "Supply goals, specific requirements, examples, and relevant code context; avoid ambiguous references."),
  responsible: source("github-responsible", "Responsible use of GitHub Copilot Agents", "GitHub", "https://docs.github.com/en/copilot/responsible-use/agents", "Generated code and review comments can be wrong; human review and testing remain necessary."),
  small: source("google-small", "Small CLs", "Google Engineering Practices", "https://google.github.io/eng-practices/review/developer/small-cls.html", "Self-contained changes with related tests are easier to review; small does not mean arbitrary line limits."),
  review: source("google-review", "What to look for in a code review", "Google Engineering Practices", "https://google.github.io/eng-practices/review/reviewer/looking-for.html", "Review overall design, behavior, complexity, tests, and maintainability."),
  testing: source("playwright-testing", "Best Practices", "Playwright", "https://playwright.dev/docs/best-practices", "Browser tests should focus on user-visible behavior and use isolated test state."),
  access: source("owasp-authorization", "Authorization Cheat Sheet", "OWASP", "https://cheatsheetseries.owasp.org/cheatsheets/Authorization_Cheat_Sheet.html", "Least privilege, default denial, and server-side permission checks on every request."),
  secrets: source("owasp-secrets", "Secrets Management Cheat Sheet", "OWASP", "https://cheatsheetseries.owasp.org/cheatsheets/Secrets_Management_Cheat_Sheet.html", "Central secret management, limited access, and a supported rotation process."),
  workflow: source("ahrq-workflow", "Workflow Assessment for Health IT: Examples", "AHRQ", "https://digital.ahrq.gov/health-it-tools-and-resources/evaluation-resources/workflow-assessment-health-it-toolkit/examples", "Assess workflow throughout planning, selection, implementation, and use; the toolkit concerns ambulatory health IT."),
  patient: source("fda-patient-input", "Patient-Focused Drug Development: Collecting Comprehensive and Representative Input", "FDA", "https://www.fda.gov/media/139088/download", "June 2020 nonbinding guidance: define research questions, target populations, and suitable sampling methods for patient experience data."),
  promotion: source("fda-promotion", "OPDP Frequently Asked Questions", "FDA", "https://www.fda.gov/about-fda/center-drug-evaluation-and-research-cder/opdp-frequently-asked-questions-faqs", "Prescription drug advertising must not be false or misleading and must fairly present effectiveness and risk; requirements vary by format."),
  minimum: source("hhs-minimum", "Minimum Necessary Requirement", "HHS", "https://www.hhs.gov/hipaa/for-professionals/privacy/guidance/minimum-necessary-requirement/index.html", "HIPAA generally limits relevant uses, requests, and disclosures to the minimum necessary, with exceptions including provider treatment disclosures and requests."),
  deidentify: source("hhs-deidentification", "Guidance Regarding Methods for De-identification", "HHS", "https://www.hhs.gov/hipaa/for-professionals/special-topics/de-identification/index.html", "HIPAA de-identification uses Expert Determination or Safe Harbor; simply removing a name does not establish compliance."),
  accessRule: source("cms-prior-auth", "Interoperability: General FAQs", "CMS", "https://www.cms.gov/initiatives/burden-reduction/overview/interoperability/frequently-asked-questions/general", "CMS-0057-F excluded drugs from its prior authorization API and process requirements; later proposals must not be confused with that finalized scope."),
  risk: source("nist-profile", "Generative Artificial Intelligence Profile", "NIST", "https://nvlpubs.nist.gov/nistpubs/ai/NIST.AI.600-1.pdf", "Confabulation, empirically evaluating capability claims, checking citations, and avoiding generalization from narrow anecdotal tests; voluntary risk guidance."),
};
export const foundationReview = "Researched and reviewed against the linked primary sources on September 15, 2026. Fictional scenarios, measurements, and suggested project decisions are original teaching examples, not reported deployments or external expert review. Healthcare lessons teach product design, not patient-specific medical or legal advice.";
