import { sqliteTable, text, integer, primaryKey, index, uniqueIndex } from "drizzle-orm/sqlite-core";
export const owner = sqliteTable("owner", { id: integer("id").primaryKey(), userId: text("user_id").notNull(), createdAt: integer("created_at").notNull() });
export const lessons = sqliteTable("lesson_versions", { key: text("key").primaryKey(), lessonId: text("lesson_id").notNull(), version: integer("version").notNull(), courseId: text("course_id").notNull(), content: text("content").notNull(), status: text("status").notNull().default("ready"), releaseInfo: text("release_info"), createdAt: integer("created_at").notNull() }, t => [index("lesson_course").on(t.courseId), uniqueIndex("lesson_identity_version").on(t.lessonId, t.version)]);
export const progress = sqliteTable("progress", { userId: text("user_id").notNull(), lessonKey: text("lesson_key").notNull(), position: integer("position").notNull().default(0), section: integer("section").notNull().default(0), completed: integer("completed").notNull().default(0), observedAt: integer("observed_at").notNull(), revision: integer("revision").notNull().default(1), positionAt: integer("position_at").notNull().default(0), sectionAt: integer("section_at").notNull().default(0) }, t => [primaryKey({ columns: [t.userId, t.lessonKey] })]);
export const events = sqliteTable("events", { id: text("id").primaryKey(), userId: text("user_id").notNull(), kind: text("kind").notNull(), payload: text("payload").notNull(), createdAt: integer("created_at").notNull() }, t => [index("events_user_time").on(t.userId, t.createdAt)]);
export const activity = sqliteTable("activity", { userId: text("user_id").notNull(), minute: integer("minute").notNull(), low: integer("low").notNull().default(0), high: integer("high").notNull().default(0) }, t => [primaryKey({ columns: [t.userId, t.minute] })]);
export const notes = sqliteTable("notes", { id: text("id").primaryKey(), userId: text("user_id").notNull(), lessonKey: text("lesson_key").notNull(), kind: text("kind").notNull(), text: text("text").notNull(), createdAt: integer("created_at").notNull() }, t => [index("notes_user_lesson").on(t.userId, t.lessonKey)]);
export const media = sqliteTable("media", { lessonKey: text("lesson_key").primaryKey(), objectKey: text("object_key").notNull(), contentType: text("content_type").notNull(), bytes: integer("bytes").notNull(), duration: integer("duration"), createdAt: integer("created_at").notNull() });
export const spending = sqliteTable("spending", { id: text("id").primaryKey(), month: text("month").notNull(), kind: text("kind").notNull(), status: text("status").notNull(), reserved: integer("reserved").notNull(), charged: integer("charged"), basis: text("basis").notNull(), providerRequest: text("provider_request"), result: text("result"), jobToken: text("job_token"), createdAt: integer("created_at").notNull(), updatedAt: integer("updated_at").notNull() }, t => [index("spending_month").on(t.month)]);
export const spendReviews = sqliteTable("spend_reviews", { id: text("id").primaryKey(), spendingId: text("spending_id").notNull(), userId: text("user_id").notNull(), revision: integer("revision").notNull(), snapshot: text("snapshot").notNull(), decision: text("decision").notNull(), amount: integer("amount"), evidence: text("evidence").notNull(), createdAt: integer("created_at").notNull() }, t => [uniqueIndex("spend_review_revision").on(t.spendingId, t.revision)]);
export const narrationReplacements = sqliteTable("narration_replacements", { id: text("id").primaryKey(), userId: text("user_id").notNull(), rootId: text("root_id").notNull(), operationId: text("operation_id").notNull(), parentId: text("parent_id").notNull(), reviewId: text("review_id").notNull(), snapshot: text("snapshot").notNull(), lessonKey: text("lesson_key").notNull(), part: integer("part").notNull(), attempt: integer("attempt").notNull(), inputSha256: text("input_sha256").notNull(), maxCost: integer("max_cost").notNull(), createdAt: integer("created_at").notNull() }, t => [uniqueIndex("narration_replacement_parent").on(t.parentId), uniqueIndex("narration_replacement_operation").on(t.operationId), uniqueIndex("narration_replacement_attempt").on(t.rootId, t.attempt)]);
export const preferences = sqliteTable("preferences", { userId: text("user_id").notNull(), key: text("key").notNull(), value: text("value").notNull(), updatedAt: integer("updated_at").notNull() }, t => [primaryKey({ columns: [t.userId, t.key] })]);
export const libraryItems = sqliteTable("library_items", { id: text("id").primaryKey(), userId: text("user_id").notNull(), kind: text("kind").notNull(), title: text("title").notNull(), url: text("url"), detail: text("detail").notNull().default(""), status: text("status").notNull().default("saved"), createdAt: integer("created_at").notNull(), refreshOf: text("refresh_of"), refreshHash: text("refresh_hash") }, t => [index("library_user").on(t.userId), index("library_refresh").on(t.refreshOf, t.userId)]);
export const generationLock = sqliteTable("generation_lock", { id: integer("id").primaryKey(), jobId: text("job_id").notNull(), createdAt: integer("created_at").notNull(), token: text("token").notNull().default(""), expiresAt: integer("expires_at").notNull().default(0) });
export const storageAllocations = sqliteTable("storage_allocations", { id: text("id").primaryKey(), bytes: integer("bytes").notNull(), status: text("status").notNull(), updatedAt: integer("updated_at").notNull() });
export const questions = sqliteTable("questions", { id: text("id").primaryKey(), userId: text("user_id").notNull(), lessonKey: text("lesson_key").notNull(), question: text("question").notNull(), sourceCaptureIds: text("source_capture_ids").notNull().default("[]"), answer: text("answer"), createdAt: integer("created_at").notNull() }, t => [index("questions_user_lesson").on(t.userId, t.lessonKey)]);
export const transcriptions = sqliteTable("transcriptions", { id: text("id").primaryKey(), userId: text("user_id").notNull(), lessonKey: text("lesson_key").notNull(), purpose: text("purpose").notNull(), audioHash: text("audio_hash").notNull(), durationMs: integer("duration_ms").notNull(), result: text("result"), createdAt: integer("created_at").notNull() }, t => [index("transcriptions_user_lesson").on(t.userId, t.lessonKey)]);
export const sourceCaptures = sqliteTable("source_captures", { id: text("id").primaryKey(), userId: text("user_id").notNull(), libraryItemId: text("library_item_id").notNull(), requestedUrl: text("requested_url").notNull(), status: text("status").notNull(), result: text("result"), material: text("material"), error: text("error"), createdAt: integer("created_at").notNull(), finishedAt: integer("finished_at") }, t => [index("source_captures_user_item").on(t.userId, t.libraryItemId), index("source_captures_created").on(t.createdAt)]);
export const topicResearch = sqliteTable("topic_research", { id: text("id").primaryKey(), userId: text("user_id").notNull(), topicId: text("topic_id").notNull(), title: text("title").notNull(), detail: text("detail").notNull(), search: text("search"), error: text("error"), createdAt: integer("created_at").notNull() }, t => [index("research_user_topic").on(t.userId, t.topicId), index("research_created").on(t.createdAt)]);
export const lessonPreparations = sqliteTable("lesson_preparations", { id: text("id").primaryKey(), userId: text("user_id").notNull(), topicId: text("topic_id").notNull(), inputs: text("inputs").notNull(), inspection: text("inspection"), draft: text("draft"), review: text("review"), error: text("error"), createdAt: integer("created_at").notNull(), updatedAt: integer("updated_at").notNull() }, t => [index("preparations_user_topic").on(t.userId, t.topicId), index("preparations_created").on(t.createdAt)]);

export const questionResearch = sqliteTable("question_research", { questionId: text("question_id").primaryKey(), userId: text("user_id").notNull(), lessonKey: text("lesson_key").notNull(), question: text("question").notNull(), topicId: text("topic_id").notNull(), researchId: text("research_id").notNull(), answerId: text("answer_id").notNull(), sourceCaptureIds: text("source_capture_ids"), createdAt: integer("created_at").notNull() }, t => [uniqueIndex("question_research_topic").on(t.topicId), uniqueIndex("question_research_run").on(t.researchId), uniqueIndex("question_research_answer").on(t.answerId), index("question_research_user").on(t.userId)]);
export const weeklyBatches = sqliteTable("weekly_batches", { userId: text("user_id").notNull(), week: text("week").notNull(), origin: text("origin").notNull(), items: text("items").notNull(), createdAt: integer("created_at").notNull() }, t => [primaryKey({ columns: [t.userId, t.week] })]);
export const weeklyChoices = sqliteTable("weekly_choices", { userId: text("user_id").notNull(), week: text("week").notNull(), itemId: text("item_id").notNull(), dismissed: integer("dismissed").notNull().default(0), revision: integer("revision").notNull().default(1), updatedAt: integer("updated_at").notNull() }, t => [primaryKey({ columns: [t.userId, t.week, t.itemId] })]);
export const weeklyRefreshes = sqliteTable("weekly_refreshes", { userId: text("user_id").notNull(), week: text("week").notNull(), origin: text("origin").notNull(), lessonKey: text("lesson_key"), lessonTitle: text("lesson_title"), reason: text("reason").notNull(), topicId: text("topic_id").notNull(), researchId: text("research_id").notNull(), preparationId: text("preparation_id").notNull(), createdAt: integer("created_at").notNull() }, t => [primaryKey({ columns: [t.userId, t.week] }), uniqueIndex("weekly_refresh_topic").on(t.topicId), uniqueIndex("weekly_refresh_research").on(t.researchId), uniqueIndex("weekly_refresh_preparation").on(t.preparationId)]);

// Google usage stays separate from the immutable OpenAI cost history.
export const chirpRequests = sqliteTable("chirp_requests", { id: text("id").primaryKey(), audioId: text("audio_id").notNull(), inputSha256: text("input_sha256").notNull(), characters: integer("characters").notNull(), status: text("status").notNull(), createdAt: integer("created_at").notNull() }, t => [index("chirp_requests_created").on(t.createdAt), index("chirp_requests_status").on(t.status)]);
export const chirpAudio = sqliteTable("chirp_audio", { id: text("id").primaryKey(), voice: text("voice").notNull(), kind: text("kind").notNull(), lessonKey: text("lesson_key"), inputSha256: text("input_sha256").notNull(), objectKey: text("object_key"), bytes: integer("bytes"), duration: integer("duration"), createdAt: integer("created_at").notNull() });
export const chirpSettings = sqliteTable("chirp_settings", { id: integer("id").primaryKey(), voice: text("voice").notNull() });
export const planDeliveries = sqliteTable("plan_deliveries", { userId: text("user_id").notNull(), week: text("week").notNull(), fingerprint: text("fingerprint").notNull(), result: text("result").notNull(), createdAt: integer("created_at").notNull() }, t => [primaryKey({ columns: [t.userId, t.week] })]);
